### ISSUE TITLE
destructuring.md存在笔误

### ISSUE THREAD

**Issue by wangyue1994** [porcelainHeart/ES6-study-notes#4]
问题：这句话（注意被赋值的是同名属性的值，这里是name 而不是firseName），应该是firstName吧。

**Comment by jw-foss** [comment]
@wangyue1994 我稍微看了一下上下文, 这句话是正确的. 从这一段代码的角度说
> `let {firstName: name, lastName} = {firstName: "John", lastName: "Doe"}`

这段代码是把 `"John"` 这个字符串的字面量赋值给了name这个变量而非 firstName这个变量.
从右手解构, 对应把右边`firstName` 匹配给了左边的`firstName`然后再把值赋给 `name`.

再具体给你解释一下原因:
左边的写法
> `let {firstName: name, lastName}` 是下面这种写法的syntax sugar(语法糖):

`let {firstName: name, lastName: lastName}`
从这里可以看到键名(key)对应匹配, 值是赋给了 `name` 和 `lastName`
